# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-03 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploader',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
