# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-03 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_auto_20190103_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='uploader',
            name='image',
        ),
        migrations.AddField(
            model_name='file',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaders', to='uploader.Uploader'),
        ),
    ]
